main/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uploader.urls', namespace='uploader')),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

uploader/urls.py
from django.urls import path

from .views import create_media, file_upload


app_name = 'uploader'

urlpatterns = [
	path('', create_media , name='create_media'),
	path('uploader/', file_upload , name='uploader'),
]

uploader/models.py
from django.core.files.uploadedfile import InMemoryUploadedFile, TemporaryUploadedFile
from django.db.models.signals import post_delete
from django.core.files.base import ContentFile
from django.dispatch import receiver
from django.db import models
import os


class ChunkedUpload(models.Model):

    STATUS_CHOICES = [
        ('started', 'Started'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]

    filename = models.CharField(max_length=255)
    file = models.FileField(upload_to='')
    offset = models.BigIntegerField(default=0)
    total_size = models.BigIntegerField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='started')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def append_chunk(self, chunk):
        try:
            # If chunk is an InMemoryUploadedFile or TemporaryUploadedFile, read the data
            if isinstance(chunk, (InMemoryUploadedFile, TemporaryUploadedFile)):
                chunk = chunk.read()

            if self.file:
                # If a file has already been uploaded, append the chunk to it
                with open(self.file.path, 'ab') as destination:
                    # Seek to the end of the file to append the new chunk
                    destination.seek(0, os.SEEK_END)
                    destination.write(chunk)
            else:
                # If no file has been uploaded yet, create a new file with the chunk
                self.file.save(self.filename, ContentFile(chunk))

            # Update the offset
            self.offset = self.file.size
            self.save()

        except Exception as e:
            self.status = 'failed'
            self.save()
            raise e


    def check_completion(self):
        if self.offset >= self.total_size:
            self.status = 'completed'
            self.save()

    def __str__(self):
        return self.filename


@receiver(post_delete, sender=ChunkedUpload)
def delete_media_file(sender, instance, **kwargs):
    instance.file.delete(False) 

uploader/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.http import JsonResponse

from .models import ChunkedUpload


@csrf_exempt
def create_media(request):
    return render(request, 'temp_media/media_form.html')

@csrf_exempt
def file_upload(request):
        data = request.POST
        chunk = request.FILES.get('chunk')
        upload_id = data.get('upload_id')

        if upload_id and upload_id != 'null':
            upload = ChunkedUpload.objects.get(id=upload_id)
        else:
            filename = data.get('filename')
            total_size = int(data.get('total_size'))
            upload = ChunkedUpload.objects.create(filename=filename, total_size=total_size)

        upload.append_chunk(chunk)
        upload.check_completion()

        if upload.status == 'completed':

            return JsonResponse({
                'upload_id': upload.id,
                'status': upload.status,
                'file_url': upload.file.url,
            })
        else:
            # If the upload is not complete, return a response with the current offset
            return JsonResponse({
                'upload_id': upload.id,
                'status': upload.status,
                'offset': upload.offset,
            })

uploader/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	
	<title>{% block title %}{% endblock title %} </title>
	<style>
		.jumbotron{
			background-color: #f8f9fa;
			padding: 28px;
			margin-bottom: 20px;
		}

	</style>
</head>
<body>
	<a class="nav-link active" aria-current="page" href="{% url 'uploader:create_media' %}" style="font-weight: bold; color: #ffffff; background-color: #343a40; padding: 5px 10px;">Home</a>
	<div class="jumbotron">
		{% block content %}{% endblock content %}
	</div>
	{% block extra_js %}{% endblock extra_js %}
</body>
</html>

uploader/templates/temp_media/media_form.html
{% extends 'base.html' %}
{% block title %}Media Form{% endblock title %}

{% block content %}
    <div class="container">
        <h4 class="display-4 text-center mb-4">Upload Media</h4>
        <form method="post" enctype="multipart/form-data" id="upload-form">
            <div class="mb-3">
                <label for="file" class="form-label">File</label>
                <input type="file" class="form-control" id="file" name="file" multiple>
            </div>
        
            <div class="progress">
                <div id="progress" class="progress-bar bg-primary" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
           
        </form>
    </div>
{% endblock content %}

{% block extra_js %}
<script>
    const fileInput = document.getElementById('file');
    fileInput.addEventListener('change', function() {
        const files = fileInput.files;
        for (let i = 0; i < files.length; i++) {
            const file = {
                file: files[i],
                offset: 0,
                upload_id: null,
                progress: 0,
                status: 0, // 0: not started, 1: uploading, 2: completed, 3: failed
                link: null
            }
            uploadNextChunk(file);
        }
    });

    const uploadNextChunk = (file) => {
    
    file.status = 1 // uploading
    var xhr = new XMLHttpRequest();
    xhr.open('POST', `http://127.0.0.1:8000/uploader/`, true);
        xhr.upload.addEventListener('progress', function(e) {
            if (e.lengthComputable) {
                var totalProgress = ((file.offset + e.loaded) / file.file.size) * 100;
                file.progress = Math.round(totalProgress)
                document.getElementById('progress').style.width = totalProgress + '%';
            }
        }, false);

        xhr.onload = function(e) {
            if (xhr.status === 200) {
                var response = JSON.parse(xhr.responseText);
                file.upload_id = response.upload_id;
                file.offset = response.offset;

                if (response.status === 'completed') {
            file.status = 2 // upload completed
            file.link = response.file_url
                } else {
                    uploadNextChunk(file);
                }
            } else {
        file.status = 3 // upload failed
            }
        };
        
        var chunk = file.file.slice(file.offset, file.offset + (1024*1024*5)); // 5MB
        var formData = new FormData();
        formData.append('chunk', chunk);
        formData.append('upload_id', file.upload_id);
        formData.append('filename', file.file.name);
        formData.append('total_size', file.file.size);
        xhr.send(formData);
    }
    const dataURLtoFile = (dataurl, filename) => {
        var arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1],
            bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);
        while(n--){
            u8arr[n] = bstr.charCodeAt(n);
        }
        return new File([u8arr], filename, {type:mime});
    }
</script>
{% endblock extra_js %}